os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64  PUID=1000 PGID=1000 JVVMAJOR=7
  - ARCH=x86_64  PUID=1000 PGID=1000 JVVMAJOR=8
  - ARCH=x86_64  PUID=1000 PGID=1000 JVVMAJOR=9
  - ARCH=x86_64  PUID=1000 PGID=1000 JVVMAJOR=10
  - ARCH=x86_64  PUID=1000 PGID=1000 JVVMAJOR=11
  - ARCH=aarch64 PUID=1001 PGID=1001 JVVMAJOR=7
  - ARCH=aarch64 PUID=1001 PGID=1001 JVVMAJOR=8
  - ARCH=aarch64 PUID=1001 PGID=1000 JVVMAJOR=9
  - ARCH=aarch64 PUID=1001 PGID=1000 JVVMAJOR=10
  - ARCH=aarch64 PUID=1001 PGID=1000 JVVMAJOR=11
  - ARCH=armhf   PUID=1001 PGID=1001 JVVMAJOR=7
  - ARCH=armhf   PUID=1001 PGID=1001 JVVMAJOR=8
  - ARCH=armv7l  PUID=1001 PGID=1001 JVVMAJOR=7
  - ARCH=armv7l  PUID=1001 PGID=1001 JVVMAJOR=8
before_script:
- uname -a
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} BRANCH=${TRAVIS_BRANCH} JVVMAJOR=${JVVMAJOR} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} JVVMAJOR=${JVVMAJOR} push
after_script:
- docker logout
- make clean
