sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000 JVVMAJOR=7
  - ARCH=x86_64 PUID=1000 PGID=1000 JVVMAJOR=8
  - ARCH=armhf  PUID=1001 PGID=1001 JVVMAJOR=7
  - ARCH=armhf  PUID=1001 PGID=1001 JVVMAJOR=8
  global:
  - secure: LGOFivLqaZl63e6gi5f5t7vWtCUQ0tYIZFhZCCCTJJ+I9WmQbZxlXGlzxManFm76nzQoSo+8vYhFgrV3dpcJrEkVo48gdWChLgIcq5xnHLrwcL8la7hVW+ejif5iJ8xXueIshgA7VtYuOzsg5WEkVZUSfFmDgXU3CaRD1qTRNRQlhSMRzkD0vMyivwLRno8bosjjykODNBAagIT8BviEBc9B5OOzbf6vzF7h2O4/ooYiz/u0jzcBiZn0fnP3VdNPlj6AjBoVwNrSNFHg1mjubfOTiPzyu5etOgDJvdW1/iwn1zns2WKZbpuejWSh1pK7t4FJPbs1a/4aHe+kpyJmXbuEh8y4GahtA4GO9XrkbUbdRD5EAXBosF4eszBLXsoEkSYLVjARUDRHUjpf0rCuOSNuaofZ8oJDkOb5Pz8wM904l/C6qyrl+HuSSaJM7Xn89ix5LyDqToI1xAN1pQ9KWlW2rt+Du1gC7kvk4YORMmZPEpT6j7QLPU3ZjoWmvmadrao5cnR8M0GywqtFvjbTvBe6vDTvTTfXZweTeWMl9A7+DL9n61Ckvm27wOqThs1LHqExPb2q5b+5+l3/82Fk6YV1bTyJmGATRq48/A+fwQ5sorx8N8fFtatG7RldC7oSwel4dwEsifB3Q7xYKskbeYVfjHc4cq+g0EfQiCqz1fw=
  - secure: kBpdKNFEFmyyJy9ut2PhI4B8c/dFZaAAdF5cepFZfSE2vRFs9FoRabOg+psYOyEdDn+H33dmNyRisMsBoYKBcUS7egqUHvJCWZrNOIHxZpqnCkkpHOkATg2/4gf+C3ZOwS/7O4ha/4+gibKLl2KHGdsf17JTSfgdqPSBU3/fSD9fDaYbcYsyOPaTqt8LqVyAXcS4+skCnQpPghEc1ZJlATd7FNyJwqaWh/MBPHKStOiA6bbh3noBDrnR5SfBtcCT8MLXdjJXQaRNvpYHCbQoZrX8zx75wvv03Tn2LvpDZqG5MAPiaNjptoUd1RtZ4TpsF1xtmyDQU3xfAo4cVPDyYUTUSRd1riJ4JPKO2pkRGppo1LR+mVLLAmrs9yZ0Iyl1gC/J5BygROu2IXSveWEG1mdoufp521XwYkEJGnqSB0Il6205uI8+fqnedxaIt3dyYtHOT52knCMdk4llQ7lOq9h+ibxBWPxJXFpEyBkcbmRCU1t0/jtnjbCDlXdArwWhNy4ihQXBnSY+D7Ay8IlgkTuq5o6xxz8twK9wn9QhU5eQn4XLCddyJbBOuVd/Dnu1G2aLP/FcIZ8jAELRGi8QjmfvbUWI6iaZTZZmQ1rtLEZsKzUjlX0aqvvuMnnr95h6NiPc5ZhZdfmAgaG0sycRb6XBLtyseUaqdvBhoxEi8+s=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} JVVMAJOR=${JVVMAJOR} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} JVVMAJOR=${JVVMAJOR} push
after_script:
- docker logout
- make clean
